server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Discover running docker containers via the docker socket
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Add container labels as Loki labels
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_label_org_opencontainers_image_title]
        target_label: image_title
      - source_labels: [__meta_docker_container_label_org_opencontainers_image_version]
        target_label: image_version
    pipeline_stages:
      - docker: {}
    # Fallback to file-based scraping of Docker JSON logs (covers older Docker setups)
  - job_name: docker-json
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}
